const BASE_URL = process.env.BACKEND_URL;
const AUTH_COOKIE_KEY = "HFDLKFHDIFHDHTRTROITURTLDFMNDLFHD";
const AUTH_USER_COOKIE = "AUTH_USER_ID";
export const appConfig = {
  BASE_URL,
  AUTH_COOKIE_KEY,
  AUTH_USER_COOKIE,
};
